- name: Aggiungi utente pippo solo se esiste /home/max/antani.txt
  hosts: all
  become: true

  tasks:
    - name: Verifica esistenza file antani.txt
      ansible.builtin.stat:
        path: /home/max/antani.txt
      register: file_antani

    - name: Crea utente pluto
      ansible.builtin.user:
        name: pluto
        password: "{{ 'pluto01' | password_hash('sha512') }}"
        state: present
        shell: /bin/bash
        create_home: true
      when: file_antani.stat.exists
